name: Update major version tag

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    steps:
      - uses: actions/publish-action@v0.4.1
        with:
          source-tag: ${{ github.event.release.tag_name }}
